### ISSUE TITLE
IOException from CreateMutexCore on Linux

### ISSUE THREAD

**Issue by jaanpeeter** [icarus-consulting/Xive#60]
### Expected Behavior

The Xive performs well on unix systems
The repo is testet on linux on the appveyor
### Actual Behavior

IOException when creating a mutex
### The log given by the failure.

System.IO.IOException: The filename, directory name, or volume label syntax is incorrect : 'Local/XC5WS5N0cbr2I_aEvsFwoQ=='
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at Xive.Xocument.MutexXocument.Block()
   at Xive.Xocument.MutexXocument.Nodes(String xpath)
   at Xive.Hive.MutexCatalog.Create(String id)

**Comment by Meerownymous** [comment]
@jaanpeeter good description - but please also remember to put a label (BUG)
